# Copyright 2023-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

enable: true
resources:
  enabled: false
images:
  repository: "docker.io/"
  # uncomment below section to add update bess image tag
  #tags:
  #  bess: <bess image tag>
  #  pfcpiface: <pfcp image tag>
  tags:
    bess: shivank1128/upf-epc-bess
    pfcpiface: shivank1128/upf-epc-pfcpiface
  
config:
  upf:
    name: "oaisim"
    # Enable privileged when run from VM with sriov support
    privileged: false
    sriov:
      enabled: false #default sriov is disabled in AIAB setup
    hugepage:
      enabled: false #should be enabled if dpdk is enabled
    #can be any other plugin as well, remember this plugin dictates how IP address are assigned.
    cniPlugin: macvlan
    ipam: static
    routes:
      - to: ${NODE_IP}  #This is the IP of my internet facing interface (ens3) . Replace this address with yours
        via: 169.254.1.1
    enb:
      subnet: ${RAN_SUBNET} #this is your gNB network
    access:
      iface: ${DATA_IFACE}
      ip: 192.168.252.${IP_ID}/24 #New IP address for UPF2 access interface
    core:
      iface: ${DATA_IFACE}
      ip: 192.168.250.${IP_ID}/24 #New IP address for UPF2 core interface
    cfgFiles:
      upf.json:
        mode: af_packet #this mode means no dpdk
        hwcksum: true
        log_level: "trace"
        workers: 1 #Increase the no, if you want more workers
        #max_sessions: 50000
        #table_sizes:
        #  pdrLookup: 50000
        #  appQERLookup: 200000
        #  sessionQERLookup: 100000
        #  farLookup: 150000
        gtppsc: true #extension header is enabled in 5G. Sending QFI in pdu session extension header
        cpiface:
          dnn: "internet" #keep it matching with Slice dnn
          hostname: "upf"
          #http_port: "8080"
          enable_ue_ip_alloc: false # if true then it means UPF allocates address from below pool
          ue_ip_pool: "172.${IP_UE_ID}.0.0/16" # UE ip pool is used if enable_ue_ip_alloc is set to true
        #slice_rate_limit_config:
        #  # #Uplink
        #  n6_bps: 1000000000 # 1Gbps
        #  n6_burst_bytes: 12500000 # 10ms * 1Gbps
        #  # #Downlink
        #  n3_bps: 1000000000 # 1Gbps
        #  n3_burst_bytes: 12500000 # 10ms * 1Gbps